/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "surface-container": "#eaedff",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#434655",
        "on-tertiary-fixed": "#001a42",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#dce1ff",
        "on-surface": "#131b2e",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b7c4ff",
        "on-secondary-fixed-variant": "#0039b5",
        "surface-container-highest": "#dae2fd",
        "on-background": "#131b2e",
        "on-tertiary-fixed-variant": "#004395",
        "on-secondary-container": "#fffbff",
        "error": "#ba1a1a",
        "outline": "#737686",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-high": "#e2e7ff",
        "inverse-primary": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "on-primary": "#ffffff",
        "surface-variant": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-primary-container": "#eeefff",
        "tertiary": "#0051b1",
        "tertiary-container": "#0f69dc",
        "primary": "#004ac6",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#edf0ff",
        "secondary": "#1d4ed8",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-tint": "#0053db",
        "outline-variant": "#c3c6d7",
        "surface-bright": "#faf8ff",
        "secondary-container": "#4069f2",
        "surface": "#faf8ff",
        "on-secondary-fixed": "#001551",
        "primary-container": "#2563eb",
        "on-primary-fixed": "#00174b"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "4xl": "3rem",
        "gutter": "1.5rem",
        "sm": "0.75rem",
        "sidebar-collapsed-w": "4.5rem",
        "md": "1rem",
        "header-h": "4rem",
        "none": "0rem",
        "2xl": "2rem",
        "xl": "1.5rem",
        "3xl": "2.5rem",
        "lg": "1.25rem",
        "sidebar-w": "17.5rem",
        "xs": "0.5rem",
        "2xs": "0.25rem"
      },
      fontFamily: {
        "label-md": ["Cairo"],
        "label-lg": ["Cairo"],
        "display": ["Cairo"],
        "body-lg": ["Cairo"],
        "headline-lg": ["Cairo"],
        "body-sm": ["Cairo"],
        "headline-md": ["Cairo"],
        "numeric-stat": ["Cairo"],
        "body-md": ["Cairo"],
        "headline-lg-mobile": ["Cairo"],
        "label-sm": ["Cairo"],
        "headline-sm": ["Cairo"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display": ["36px", { lineHeight: "48px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "38px", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "30px", fontWeight: "600" }],
        "numeric-stat": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg-mobile": ["22px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}